version: '3.1'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
        POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432